f1data/urls.py
from django.urls import path
from . import views

app_name = "f1data"
urlpatterns = [
    path('', views.home, name="home"),
    path('season/<int:page>/', views.Seasons.as_view(),name="seasons"),
    path('season/<int:year>/', views.detail_season, name="detail_season"),
    path('races/', views.RacesRedirectView.as_view(), name="races"),
    path('races/<int:year>/', views.Races.as_view(), name="races"),
    path('races/<int:race>/', views.detail_race, name="detail_race"),
    path('drivers/<int:year>/', views.Drivers.as_view(), name="drivers"),
    path('drivers/', views.DriversRedirectView.as_view(), name="drivers"),
    path('drivers/<int:driver>/', views.detail_driver, name="detail_driver"),
    path('constructors/', views.ConstructorsRedirectView.as_view(), name="constructors"),
    path('constructors/<int:year>/', views.Constructors.as_view(), name="constructors"),
    path('constructors/<int:constructor>/', views.detail_constructor, name="detail_constructor"),
    path('driver_standings/<int:year>/', views.DriverStandings.as_view(), name="driver_standings"),
    path('driver_standings/', views.DriverStandingsRedirectView.as_view(), name="driver_standings"),
    path('constructors_standings/<int:year>/', views.ConstructorStandings.as_view(), name="constructors_standings"),
    path('constructors_standings/', views.ConstructorStandingsRedirectView.as_view(), name="constructors_standings"),
]

f1racingdata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('f1data.urls')),
    path('admin/', admin.site.urls),
]

f1data/models.py
from django.db import models

# Create your models here.
class Season(models.Model):
    year = models.IntegerField()
    url = models.URLField(max_length=255)
    races = models.ManyToManyField('Race')
    qualifying = models.ManyToManyField('Qualifying')
    results = models.ManyToManyField('Result')
    sprint_results = models.ManyToManyField('SprintResult')
    drivers = models.ManyToManyField('Driver')
    constructors = models.ManyToManyField('Constructor')
    circuits = models.ManyToManyField('Circuit')

    class Meta:
        ordering = ['-year']

    def __str__(self):
        return f"{self.year}"

class Race(models.Model):
    race_id = models.IntegerField()
    year = models.IntegerField()
    round = models.IntegerField()
    name = models.CharField(max_length=255)
    date = models.DateField()
    time = models.TimeField(null=True)
    url = models.URLField(max_length=255)
    fp1_date = models.DateField(null=True)
    fp1_time = models.TimeField(null=True)
    fp2_date = models.DateField(null=True)
    fp2_time = models.TimeField(null=True)
    fp3_date = models.DateField(null=True)
    fp3_time = models.TimeField(null=True)
    quali_date = models.DateField(null=True)
    quali_time = models.TimeField(null=True)
    sprint_date = models.DateField(null=True)
    sprint_time = models.TimeField(null=True)
    drivers = models.ManyToManyField('Driver')
    constructors = models.ManyToManyField('Constructor')
    circuit = models.ForeignKey('Circuit',on_delete=models.PROTECT)

    class Meta:
        ordering = ['-year','-round']

    def __str__(self):
        return f"{self.year} {self.round} {self.circuit}"

class Qualifying(models.Model):
    qualify_id = models.IntegerField()
    number = models.IntegerField()
    position = models.IntegerField()
    q1 = models.CharField(max_length=255)
    q2 = models.CharField(max_length=255)
    q3 = models.CharField(max_length=255)
    driver = models.ForeignKey('Driver',on_delete=models.PROTECT)
    race = models.ForeignKey('Race',on_delete=models.PROTECT)
    constructor = models.ForeignKey('Constructor',on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.position} {self.driver} {self.race} {self.constructor}"

class Result(models.Model):
    result_id = models.IntegerField()
    number = models.IntegerField(null=True)
    grid = models.IntegerField()
    position = models.IntegerField(null=True)
    position_text = models.CharField(max_length=255)
    position_order = models.IntegerField()
    points = models.FloatField()
    laps = models.IntegerField()
    time = models.CharField(max_length=255,default="")
    milliseconds = models.IntegerField(null=True)
    fastest_lap = models.IntegerField(null=True)
    rank = models.IntegerField(null=True)
    fastest_lap_time = models.CharField(max_length=255)
    fastest_lap_speed = models.CharField(max_length=255)
    status = models.ForeignKey('Status',on_delete=models.PROTECT)
    driver = models.ForeignKey('Driver',on_delete=models.PROTECT)
    race = models.ForeignKey('Race',on_delete=models.PROTECT)
    constructor = models.ForeignKey('Constructor',on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.driver} {self.race} {self.constructor}"

class SprintResult(models.Model):
    result_id = models.IntegerField()
    number = models.IntegerField()
    grid = models.IntegerField()
    position = models.IntegerField(null=True)
    position_text = models.CharField(max_length=255)
    position_order = models.IntegerField()
    points = models.FloatField()
    laps = models.IntegerField()
    time = models.CharField(max_length=255,default="")
    milliseconds = models.IntegerField(null=True)
    fastest_lap = models.IntegerField(null=True)
    fastest_lap_time = models.CharField(max_length=255)
    status = models.ForeignKey('Status',on_delete=models.PROTECT)
    driver = models.ForeignKey('Driver',on_delete=models.PROTECT)
    race = models.ForeignKey('Race',on_delete=models.PROTECT)
    constructor = models.ForeignKey('Constructor',on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.driver} {self.race} {self.constructor}"

class Driver(models.Model):
    driver_id = models.IntegerField()
    driver_ref = models.CharField(max_length=255)
    number = models.IntegerField(null=True)
    code = models.CharField(max_length=3)
    forename = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    dob = models.DateField()
    nationality = models.CharField(max_length=255)
    url = models.URLField(max_length=255)

    def __str__(self):
        return f"{self.surname} {self.forename} {self.code} {self.number}"

class Constructor(models.Model):
    constructor_id = models.IntegerField()
    constructor_ref = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    nationality = models.CharField(max_length=255)
    url = models.URLField(max_length=255)

    def __str__(self):
        return f"{self.constructor_id} {self.name}"

class Circuit(models.Model):
    circuit_id = models.IntegerField()
    circuit_ref = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    lat = models.FloatField()
    lng = models.FloatField()
    alt = models.IntegerField(null=True)
    url = models.URLField(max_length=255)

    def __str__(self):
        return f"{self.name}"

class Status(models.Model):
    status_id = models.IntegerField()
    status = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.status_id} {self.status}"

class PitStop(models.Model):
    stop = models.IntegerField()
    lap = models.IntegerField()
    time = models.TimeField()
    duration = models.CharField(max_length=255)
    milliseconds = models.IntegerField()
    race = models.ForeignKey('Race',on_delete=models.PROTECT)
    driver = models.ForeignKey('Driver',on_delete=models.PROTECT)

class LapTime(models.Model):
    lap = models.IntegerField()
    position = models.IntegerField()
    time = models.CharField(max_length=255)
    milliseconds = models.IntegerField()
    race = models.ForeignKey('Race',on_delete=models.PROTECT)
    driver = models.ForeignKey('Driver',on_delete=models.PROTECT)

class DriverStanding(models.Model):
    driver_standing_id = models.IntegerField()
    points = models.FloatField()
    position = models.IntegerField()
    position_text = models.CharField(max_length=255)
    wins = models.IntegerField()
    race = models.ForeignKey('Race',on_delete=models.PROTECT)
    driver = models.ForeignKey('Driver',on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.driver} {self.race}"

class ConstructorStanding(models.Model):
    constructor_standings_id = models.IntegerField()
    points = models.FloatField()
    position = models.IntegerField()
    position_text = models.CharField(max_length=255)
    wins = models.IntegerField()
    race = models.ForeignKey('Race',on_delete=models.PROTECT)
    constructor = models.ForeignKey('Constructor',on_delete=models.PROTECT,default=None)

class ConstructorResult(models.Model):
    constructor_result_id = models.IntegerField()
    points = models.FloatField()
    status = models.CharField(max_length=255)
    race = models.ForeignKey('Race',on_delete=models.PROTECT)
    constructor = models.ForeignKey('Constructor',on_delete=models.PROTECT,default=None)

f1data/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.views.generic.base import RedirectView
from f1data.models import *

# Create your views here.
def home(request):
    template = "f1data/home/home.html"
    current_season = Season.objects.first()
    last_race = DriverStanding.objects.order_by("race").first().race
    if last_race.round < current_season.races.count():
        next_race = current_season.races.get(round=last_race.round + 1)
    else:
        next_race = None

    results = Result.objects.filter(race=last_race)
    sprint_results = SprintResult.objects.filter(race=last_race)
    qualifying = Qualifying.objects.filter(race=last_race)
    driver_standings = DriverStanding.objects.filter(race=last_race).order_by('position')
    constructor_standings = ConstructorStanding.objects.filter(race=last_race).order_by('position')
    constructor_results = ConstructorResult.objects.filter(race=last_race)

    context = {
        "current_season": current_season,
        "last_race": last_race,
        "next_race": next_race,
        "results": results,
        "sprint_results": sprint_results,
        "qualifying": qualifying,
        "driver_standings": driver_standings,
        "constructor_standings": constructor_standings,
        "constructor_results": constructor_results
    }
    return render(request,template,context)

class Seasons(ListView):
    model = Season
    context_object_name = 'seasons'
    paginate_by = 12
    template_name = "f1data/season/season.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_obj = context['page_obj']
        if page_obj.number > 2 and (page_obj.paginator.num_pages - page_obj.number) > 2:
            pages = range(page_obj.number-2,page_obj.number+3)
        elif page_obj.number <= 2:
            pages = range(1,5)
        elif (page_obj.paginator.num_pages - page_obj.number) <=2:
            pages = range(page_obj.paginator.num_pages-5,page_obj.paginator.num_pages+1)
        context['pages'] = pages
        return context

def detail_season(request,year):
    return HttpResponse("Detail Season")

class RacesRedirectView(RedirectView):
    year = Season.objects.first().year
    url = f'{year}/'

class Races(ListView):
    template_name = 'f1data/races/races.html'
    context_object_name = 'races'

    def get_queryset(self,**kwargs):
        year = self.__dict__['kwargs']['year']
        return Race.objects.filter(year=year)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        seasons = Season.objects.values('year')
        context['seasons'] = seasons
        context['year'] = self.__dict__['kwargs']['year']
        return context

def detail_race(request,race):
    return HttpResponse("Detail Race")

class DriversRedirectView(RedirectView):
    year = Season.objects.first().year
    url = f'{year}/'

class Drivers(ListView):
    template_name = "f1data/drivers/drivers.html"
    context_object_name = 'drivers'

    def get_queryset(self,*kwargs):
        year = self.__dict__['kwargs']['year']
        return Season.objects.get(year=year).drivers.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        seasons = Season.objects.values('year')
        context['seasons'] = seasons
        context['year'] = self.__dict__['kwargs']['year']
        return context

def detail_driver(request,driver):
    return HttpResponse("Detail Driver")

class ConstructorsRedirectView(RedirectView):
    year = Season.objects.first().year
    url = f'{year}'

class Constructors(ListView):
    template_name = "f1data/constructors/constructors.html"
    context_object_name = 'constructors'

    def get_queryset(self,**kwargs):
        year = self.__dict__['kwargs']['year']
        return Season.objects.get(year=year).constructors.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        seasons = Season.objects.values('year')
        context['seasons'] = seasons
        context['year'] = self.__dict__['kwargs']['year']
        return context

def detail_constructor(request,constructor):
    return HttpResponse("Detail Constructor")

class DriverStandingsRedirectView(RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        year = Season.objects.first().year
        round = DriverStanding.objects.order_by("race").first().race.round
        return f"{year}/"

class DriverStandings(ListView):
    template_name = "f1data/driver_standings/driver_standings.html"
    context_object_name = 'driver_standings'

    def get_queryset(self,**kwargs):
        year = self.kwargs['year']
        races = Race.objects.filter(year=year)
        driver_standings = []
        for race in races:
            query_set = DriverStanding.objects.filter(race=race).order_by('position')
            if query_set.exists():
                driver_standings.append(query_set)
        return driver_standings

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        rounds = []
        season = self.kwargs['year']
        context['current_season'] = Season.objects.get(year=season)
        context['seasons'] = Season.objects.values('year')
        races = Race.objects.filter(year=season).order_by('round')

        for race in races:
            if DriverStanding.objects.filter(race=race).exists():
                rounds.append(race)

        context['races'] = rounds
        return context

class ConstructorStandingsRedirectView(RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        year = Season.objects.first().year
        round = DriverStanding.objects.order_by("race").first().race.round
        return f"{year}/"

class ConstructorStandings(ListView):
    template_name = "f1data/constructor_standings/constructor_standings.html"
    context_object_name = 'constructor_standings'

    def get_queryset(self,**kwargs):
        year = self.kwargs['year']
        races = Race.objects.filter(year=year)
        constructor_standings = []
        for race in races:
            query_set = ConstructorStanding.objects.filter(race=race).order_by('position')
            if query_set.exists():
                constructor_standings.append(query_set)
        return constructor_standings

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        rounds = []
        season = self.kwargs['year']
        context['current_season'] = Season.objects.get(year=season)
        context['seasons'] = Season.objects.values('year')
        races = Race.objects.filter(year=season).order_by('round')

        for race in races:
            if ConstructorStanding.objects.filter(race=race).exists():
                rounds.append(race)

        context['races'] = rounds
        return context

f1data/templates/f1data/content/constructor_standings.html
{% load driver_constructor %}
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col-1">
      <button class="btn btn-secondary dropdown-toggle me-3" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        {{ current_season }}
      </button>
      <ul class="dropdown-menu">
        {% for season in seasons %}
        <li><a class="dropdown-item {% if year == season.year %}active{% endif %}" href="{% url 'f1data:constructors_standings' season.year %}">{{season.year}}</a></li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-2">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Choose Round
        </button>
        <ul class="dropdown-menu">
          {% for race in races %}
          <li><a class="dropdown-item" href="#{{race.round}}">{{race.round}}</a></li>
          {% endfor %}
        </ul>
    </div>
  </div>
  <div class="row row-cols-3 row-cols-xs-1 row-cols-sm-1 row-cols-md-1 row-cols-lg-2 my-2 g-3">
    {% for standing in constructor_standings %}
    <div class="col">
      <div id="{{standing.first.race.round}}" class="card">
        <div class="card-header">
          <h5 class="card-title">{{standing.first.race.name}} <br>Round: {{standing.first.race.round}}</h5>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Position</th>
                <th scope="col">Constructor</th>
                <th scope="col">Points</th>
                <th scope="col">Wins</th>
              </tr>
            </thead>
            <tbody>
              {% for constructor in  standing%}
              <tr>
                <td scope="row">{{ constructor.position }} </td>
                <td>{{ constructor.constructor.name }}</td>
                <td>{{ constructor.points }}</td>
                <td>{{ constructor.wins }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

f1data/templates/f1data/content/constructors.html
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col-2">
      <div class="dropdown-center">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          {{ year }}
        </button>
        <ul class="dropdown-menu">
          {% for season in seasons %}
          <li><a class="dropdown-item {% if year == season.year %}active{% endif %}" href="{% url 'f1data:constructors' season.year %}">{{season.year}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="row row-cols-3 row-cols-sm-1 row-cols-md-3 my-3 g-3">
    {% for constructor in constructors %}
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{constructor.name}}</h5>
          <a href="{% url 'f1data:detail_constructor' constructor.constructor_id%}" class="btn btn-primary">Constructor Details</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

f1data/templates/f1data/content/driver_standings.html
{% load driver_constructor %}
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col-1">
      <button class="btn btn-secondary dropdown-toggle me-3" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        {{ current_season }}
      </button>
      <ul class="dropdown-menu">
        {% for season in seasons %}
        <li><a class="dropdown-item {% if year == season.year %}active{% endif %}" href="{% url 'f1data:driver_standings' season.year %}">{{season.year}}</a></li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-2">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Choose Round
        </button>
        <ul class="dropdown-menu">
          {% for race in races %}
          <li><a class="dropdown-item" href="#{{race.round}}">{{race.round}}</a></li>
          {% endfor %}
        </ul>
    </div>
  </div>
  <div class="row row-cols-3 row-cols-xs-1 row-cols-sm-1 row-cols-md-1 row-cols-lg-2 my-2 g-3">
    {% for standing in driver_standings %}
    <div class="col">
      <div id="{{standing.first.race.round}}" class="card">
        <div class="card-header">
          <h5 class="card-title">{{standing.first.race.name}} <br>Round: {{standing.first.race.round}}</h5>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Position</th>
                <th scope="col">Name</th>
                <th scope="col">Constructor</th>
                <th scope="col">Points</th>
                <th scope="col">Wins</th>
              </tr>
            </thead>
            <tbody>
              {% for driver in  standing%}
              <tr>
                <td scope="row">{{ driver.position }} </td>
                <td>{{ driver.driver.forename }} {{ driver.driver.surname }}</td>
                <td>{{ driver | constructor:current_season }}</td>
                <td>{{ driver.points }}</td>
                <td>{{ driver.wins }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

f1data/templates/f1data/content/drivers.html
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col-2">
      <div class="dropdown-center">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          {{ year }}
        </button>
        <ul class="dropdown-menu">
          {% for season in seasons %}
          <li><a class="dropdown-item {% if year == season.year %}active{% endif %}" href="{% url 'f1data:drivers' season.year %}">{{season.year}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="row row-cols-3 row-cols-sm-1 row-cols-md-3 my-3 g-3">
    {% for driver in drivers %}
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{driver.forename}} {{driver.surname}}</h5>
          <a href="{% url 'f1data:detail_driver' driver.driver_id%}" class="btn btn-primary">Driver Details</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

f1data/templates/f1data/content/races.html
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col-2">
      <div class="dropdown-center">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          {{ year }}
        </button>
        <ul class="dropdown-menu">
          {% for season in seasons %}
              <li><a class="dropdown-item {% if year == season.year %}active{% endif %}" href="{% url 'f1data:races' season.year %}">{{season.year}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="row row-cols-3 row-cols-sm-1 row-cols-md-3 my-3 g-3">
    {% for race in races %}
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{race.name}} <br />Round: {{race.round}} Year: {{race.year}}</h5>
          <a href="{% url 'f1data:detail_race' race.race_id %}" class="btn btn-primary">Race Details</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

f1data/templates/f1data/content/season.html
{% load season_results %}
<div class="container">
  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center mt-3">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="{% url 'f1data:seasons' 1 %}">First</a></li>
        <li class="page-item"><a class="page-link" href="{% url 'f1data:seasons' page_obj.previous_page_number%}">Previous</a></li>
    {% endif %}

    {% for page in pages %}
      <li class="page-item {% if page == page_obj.number %}active{% endif %}"><a class="page-link" href="{% url 'f1data:seasons' page%}">{{ page }}</a></li>
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="{% url 'f1data:seasons' page_obj.next_page_number %}">Next</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'f1data:seasons' page_obj.paginator.num_pages %}">Last</a></li>
    {% endif %}
  </ul>
</nav>
  <div class="row row-cols-3 row-cols-sm-1 row-cols-md-3 my-3 g-3">
    {% for season in seasons %}
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{season.year}}</h5>
          <table class="table">
            <thead>
              <tr>
                {% if forloop.first %}
                <th scope="col">Drivers Leader</th>
                <th scope="col">Constructors Leader</th>
                {% else %}
                <th scope="col">Drivers Champion</th>
                <th scope="col">Constructors Champion</th>
                {% endif %}
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{{season.year | driver}}</td>
                <td>{{season.year | constructor}}</td>
              </tr>
            </tbody>
          </table>
          <a href="{% url 'f1data:detail_season' season.year %}" class="btn btn-primary">Season Details</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>